version: 2.1
orbs:
  architect: giantswarm/architect@4.31.0

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit
  acceptance-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          apptestctl-version: v0.14.1
          helm-version: v3.8.2
          kubernetes-version: v1.21.1
      - run:
          name: "Run acceptance tests"
          command: CGO_ENABLED=0 make test-acceptance


workflows:
  test-and-push:
    jobs:
      - unit-tests:
          filters:
            tags:
              only: /^v.*/
      - acceptance-tests:
          filters:
            tags:
              only: /^v.*/
      - architect/go-build:
          context: architect
          name: go-build
          binary: workload-identity-operator-gcp
          resource_class: xlarge
          requires:
            - unit-tests
            - acceptance-tests
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/workload-identity-operator-gcp"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
          - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-to-docker
          image: "docker.io/giantswarm/workload-identity-operator-gcp"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
                k
    # Ensure that for every commit
    # there is an app version in the test catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "workload-identity-operator-gcp"
          requires:
          - push-to-quay
          - push-to-docker
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
