project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/workload-identity-operator-gcp"
  tag: "[[ .Version ]]"
registry:
  domain: quay.io

pod:
  user:
    id: 1000
  group:
    id: 1000
