apiVersion: v1
stringData:
  credentials: |-
    {{ .Values.gcp.credentials | b64dec | nindent 4 }}
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-gcp-credentials
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
