---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: {{ .Values.webhookPort }}
      protocol: TCP
      name: https
  selector:
  {{- include "labels.selector" . | nindent 6 }}

